POST    http://localhost:8008/api/auth/login
Content-Type: application/json

{
  "email":"mohamedeid@gmail.com",
  "password":"01003098950"
}

### register user 
POST    http://localhost:8008/api/auth/register
Content-Type: application/json

{
  "email":"mohamedeid@gmail.com",
  "password":"01003098950",
  "name":"mohamed eid"
  
}
